"""add event_outbox and processed_event tables

Revision ID: 0ec60bc5c0c2
Revises: 1da5d7f0aa92
Create Date: 2026-03-07 12:09:06.717149

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0ec60bc5c0c2"
down_revision: Union[str, None] = "1da5d7f0aa92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_outbox",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("relayed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_outbox")),
        sa.UniqueConstraint("event_id", name=op.f("uq_event_outbox_event_id")),
    )
    op.create_index(
        op.f("ix_event_outbox_event_type"), "event_outbox", ["event_type"], unique=False
    )
    op.create_index(
        "ix_event_outbox_pending",
        "event_outbox",
        ["id"],
        unique=False,
        postgresql_where=sa.text("relayed_at IS NULL"),
    )
    op.create_table(
        "processed_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("handler_group", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processed_event")),
        sa.UniqueConstraint(
            "event_id", "handler_group", name="uq_processed_event_event_id_handler_group"
        ),
    )
    op.create_index(
        op.f("ix_processed_event_event_id"), "processed_event", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_processed_event_handler_group"),
        "processed_event",
        ["handler_group"],
        unique=False,
    )
    # ### end Alembic commands ###

    # PG NOTIFY trigger: fires on every INSERT into event_outbox
    # so the outbox relay wakes up immediately instead of waiting
    # for its polling interval.
    op.execute(
        sa.text("""
        CREATE OR REPLACE FUNCTION notify_event_outbox() RETURNS trigger AS $$
        BEGIN
            PERFORM pg_notify('event_outbox_channel', NEW.id::text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    )
    op.execute(
        sa.text("""
        CREATE TRIGGER event_outbox_notify
        AFTER INSERT ON event_outbox
        FOR EACH ROW EXECUTE FUNCTION notify_event_outbox();
    """)
    )


def downgrade() -> None:
    # Drop trigger and function before tables
    op.execute(sa.text("DROP TRIGGER IF EXISTS event_outbox_notify ON event_outbox"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS notify_event_outbox()"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_event_handler_group"), table_name="processed_event")
    op.drop_index(op.f("ix_processed_event_event_id"), table_name="processed_event")
    op.drop_table("processed_event")
    op.drop_index(
        "ix_event_outbox_pending",
        table_name="event_outbox",
        postgresql_where=sa.text("relayed_at IS NULL"),
    )
    op.drop_index(op.f("ix_event_outbox_event_type"), table_name="event_outbox")
    op.drop_table("event_outbox")
    # ### end Alembic commands ###
