"""add kafka_offset and kafka_message tables

Revision ID: 1da5d7f0aa92
Revises: bd1e56f14382
Create Date: 2026-03-01 19:11:34.608226

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1da5d7f0aa92"
down_revision: Union[str, None] = "bd1e56f14382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kafka_message",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("consumer_name", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("partition", sa.BigInteger(), nullable=False),
        sa.Column("offset", sa.BigInteger(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kafka_message")),
        sa.UniqueConstraint(
            "topic", "partition", "offset", name="uq_kafka_message_topic_partition_offset"
        ),
    )
    op.create_index(
        op.f("ix_kafka_message_consumer_name"),
        "kafka_message",
        ["consumer_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kafka_message_event_name"), "kafka_message", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_kafka_message_topic"), "kafka_message", ["topic"], unique=False
    )
    op.create_table(
        "kafka_offset",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("consumer_name", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("partition", sa.BigInteger(), nullable=False),
        sa.Column("offset", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kafka_offset")),
        sa.UniqueConstraint(
            "consumer_name",
            "topic",
            "partition",
            name="uq_kafka_offset_consumer_topic_partition",
        ),
    )
    op.create_index(
        op.f("ix_kafka_offset_consumer_name"),
        "kafka_offset",
        ["consumer_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kafka_offset_consumer_name"), table_name="kafka_offset")
    op.drop_table("kafka_offset")
    op.drop_index(op.f("ix_kafka_message_topic"), table_name="kafka_message")
    op.drop_index(op.f("ix_kafka_message_event_name"), table_name="kafka_message")
    op.drop_index(op.f("ix_kafka_message_consumer_name"), table_name="kafka_message")
    op.drop_table("kafka_message")
    # ### end Alembic commands ###
